name: simple_result
version: 1.0.3
homepage: https://github.com/spielgestalt/simple_result.git
description: A simple posibility to return a Result with eiter success or failure.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  equatable: ^2.0.3
  freezed_annotation: ^1.0.0
  meta: ^1.7.0
dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^1.0.0
  lint: ^1.7.2
  test: ^1.19.3
