name: simple_result
version: 1.0.4
homepage: https://github.com/spielgestalt/simple_result.git
description: A simple posibility to return a Result with eiter success or failure.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  equatable: ^2.0.3
  freezed_annotation: ^1.1.0
  meta: ^1.7.0
dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  lint: ^1.8.2
  test: ^1.20.1
