name: simple_result
version: 1.0.1
homepage: https://github.com/spielgestalt/simple_result.git
description: A simple posibility to return a Result with eiter success or failure.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  equatable: ^2.0.3
  meta: ^1.7.0
dev_dependencies:
  lint: ^1.7.2
  test: ^1.18.2  
