name: simple_result
version: 1.0.7
homepage: https://github.com/amatkivskiy/simple_result
description: A simple posibility to return a Result with eiter success or failure.

environment:
    sdk: ">=2.18.0 <3.0.0"

dependencies:
    freezed_annotation: ^2.2.0
    meta: ^1.8.0

dev_dependencies:
    build_runner: ^2.3.2
    equatable: ^2.0.5
    freezed: ^2.2.1
    lint: ^1.10.0
    test: ^1.22.0
