name: simple_result
version: 1.0.6
homepage: https://github.com/spielgestalt/simple_result.git
description: A simple posibility to return a Result with eiter success or failure.
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  collection: ^1.16.0
  equatable: ^2.0.5
  freezed_annotation: ^2.1.0
  meta: ^1.8.0
dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.0+1
  lint: ^1.10.0
  test: ^1.21.6
