name: simple_result
version: 0.1.4
homepage: https://github.com/spielgestalt/simple_result.git
description: A simple posibility to return a Result with eiter success or failure.
environment:
  sdk: ">=2.4.0 <3.0.0"
dependencies:
  meta: ^1.1.8
dev_dependencies:
  lint: ^1.1.1
  test: ^1.12.0
  equatable: ^1.1.0
